name: Build PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Lint
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build
        uses: actions/setup-node@v1.1.0
        with:
          node-version: lts
      - run: npm ci
      - name: Lint
        uses: creyD/prettier_action@v2.1
        with:
          dry: true # no GITHUB_TOKEN yet
          prettier_options: '--write "**/*.{js,mdx}"'
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
      - run: npm run build
