name: Build PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build
        uses: actions/setup-node@v1.1.0
        with:
          node-version: lts
      - run: npm ci
      - run: npm run build
