name: Deploy Beta

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build
        uses: actions/setup-node@v1.1.0
        with:
          node-version: lts
      - run: npm ci
      - name: Deploy
      - run: npm run deploy:beta -- --token ${{ secrets.SURGE_TOKEN }}
